app/urls.py
from django.urls import path, re_path
from app import views
app_name = 'app'
urlpatterns = [

    # The home page
    path('', views.index, name='home'),
    path('fetch_sensor_values_ajax_com', views.fetch_sensor_values_ajax_com,
         name='fetch_sensor_values_ajax_com'),
    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),

]

authentication/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path
from .views import login_view, register_user
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_user, name="register"),
    path("logout/", LogoutView.as_view(), name="logout")
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("authentication.urls")), # Auth routes - login / register
    path("", include("app.urls"))             # UI Kits Html files
]

app/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

authentication/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models

# Create your models here.

authentication/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Username",                
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password",                
                "class": "form-control"
            }
        ))

class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Username",                
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder" : "Email",                
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password",                
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password check",                
                "class": "form-control"
            }
        ))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

app/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.http import HttpResponse, JsonResponse
from django import template
import serial
import random
import datetime


@login_required(login_url="/login/")
def index(request):
    
    context = {}
    context['segment'] = 'index'

    html_template = loader.get_template( 'index.html' )
    return HttpResponse(html_template.render(context, request))

@login_required(login_url="/login/")
def pages(request):
    context = {}
    # All resource paths end in .html.
    # Pick out the html file name from the url. And load that template.
    try:
        
        load_template      = request.path.split('/')[-1]
        context['segment'] = load_template
        
        html_template = loader.get_template( load_template )
        return HttpResponse(html_template.render(context, request))
        
    except template.TemplateDoesNotExist:

        html_template = loader.get_template( 'page-404.html' )
        return HttpResponse(html_template.render(context, request))

    except:
    
        html_template = loader.get_template( 'page-500.html' )
        return HttpResponse(html_template.render(context, request))


#****************
# data realtime serial arduino
def show_graph_com(request, template_name='index.html'):
    return render(request, template_name)
def fetch_sensor_values_ajax_com(request):
    data={}
    if request.is_ajax():
            sensor_data0=[]
            sensor_val=random.random()
            try:
                ser=serial.Serial("COM3",9600)
                ser_bytes = ser.readline().decode().strip().split(',')
                new_ser_bytes = [float(i) for i in ser_bytes]
                now=datetime.now()
                ok_date=str(now.strftime('%Y-%m-%d %H:%M:%S'))
                humidity = new_ser_bytes[0]
                temperature = new_ser_bytes[1]
                WaterTemp =new_ser_bytes[2]
                ph =new_ser_bytes[3]
                if humidity is not None and temperature is not None and WaterTemp is not None and ph is not None:
               
                    sensor_data0.append(str(humidity)+','+ok_date)
                    sensor_data0.append(str(temperature)+','+ok_date)
                    sensor_data0.append(str(WaterTemp)+','+ok_date)
                    sensor_data0.append(str(ph)+','+ok_date)
                    x=sensor_data0
                else:
                    sensor_data0.append(str(sensor_val)+','+ok_date)
            except Exception as e:
                    sensor_data0.append(str(sensor_val)+','+ok_date)
            data['result']=x
    else:
        data['result']='Not Ajax'
    return JsonResponse(data)

authentication/views.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.forms.utils import ErrorList
from django.http import HttpResponse
from .forms import LoginForm, SignUpForm

def login_view(request):
    form = LoginForm(request.POST or None)

    msg = None

    if request.method == "POST":

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("/")
            else:    
                msg = 'Invalid credentials'    
        else:
            msg = 'Error validating the form'    

    return render(request, "accounts/login.html", {"form": form, "msg" : msg})

def register_user(request):

    msg     = None
    success = False

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)

            msg     = 'User created - please <a href="/login">login</a>.'
            success = True
            
            #return redirect("/login/")

        else:
            msg = 'Form is not valid'    
    else:
        form = SignUpForm()

    return render(request, "accounts/register.html", {"form": form, "msg" : msg, "success" : success })

core/templates/accounts/login.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="row">
          <div class="col-md-8">
            <div class="card">

              <form role="form" method="post" action="">
              
                {% csrf_token %} 

                <div class="card-header">
                  <h5 class="title">Login</h5>

                  <h6 class="card-category">
                      {% if msg %}
                        <span class="text-danger">{{ msg | safe }}</span>
                      {% else %}
                        Add your credentials
                      {% endif %}  
                  </h6>
                </div>

                <div class="card-body">

                    <div class="row">

                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <label>Username</label>
                          {{ form.username }}
                        </div>
                      </div>

                    </div>
                    <div class="row">

                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <label>Password</label>
                          {{ form.password }}
                        </div>
                      </div>

                    </div>
                    
                </div>
                <div class="card-footer">
                  <button type="submit" name="login" class="btn btn-fill btn-primary">Login</button>
                  &nbsp; &nbsp;
                  Don't have an account? <a href="{% url 'register' %}" class="text-primary">Create</a>
                </div>

              </form>

            </div>
          </div>
      </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/accounts/register.html
{% extends "layouts/base.html" %}

{% block title %} Register {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="row">
          <div class="col-md-8">
            <div class="card">

              <form role="form" method="post" action="">
              
                {% csrf_token %} 

                <div class="card-header">
                  <h5 class="title">Register</h5>

                  <h6 class="card-category">
                      {% if msg %}
                        <span class="text-danger">{{ msg | safe }}</span>
                      {% else %}
                        Add your credentials 
                      {% endif %}  
                  </h6>
                </div>

              {% if success %}

                <p>
                  Please <a href={% url 'login' %}>authenticate</a> using the new account.
                </p>  

              {% else %}

                <div class="card-body">

                    <div class="row">
                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <label>Username</label>
                          {{ form.username }}
                        </div>
                      </div>
                    </div>
                    <span class="text-danger">{{ form.username.errors }}</span>

                    <div class="row">
                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <label>Email</label>
                          {{ form.email }}
                        </div>
                      </div>
                    </div>
                    <span class="text-danger">{{ form.email.errors }}</span>

                    <div class="row">
                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <label>Password</label>
                          {{ form.password1 }}
                        </div>
                      </div>
                    </div>
                    <span class="text-danger">{{ form.password1.errors }}</span>
                    
                    <div class="row">
                        <div class="col-md-3 px-md-1">
                            <div class="form-group">
                            <label>Password Check</label>
                            {{ form.password2 }}
                            </div>
                        </div>
                    </div>
                    <span class="text-danger">{{ form.password2.errors }}</span>

                </div>
                <div class="card-footer">
                  <button type="submit" name="register" class="btn btn-fill btn-primary">Register</button>
                  &nbsp; &nbsp;
                  Have an account? <a href="{% url 'login' %}" class="text-primary">Login</a>
                </div>

              {% endif %} 

              </form>

            </div>
          </div>
      </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

core/templates/includes/fixed-plugin.html
  <div class="fixed-plugin">
    <div class="dropdown show-dropdown">
      <a href="#" data-toggle="dropdown">
        <i class="fa fa-cog fa-2x"> </i>
      </a>
      <ul class="dropdown-menu">
        <li class="header-title"> Sidebar Background</li>
        <li class="adjustments-line">
          <a href="javascript:void(0)" class="switch-trigger background-color">
            <div class="badge-colors text-center">
              <span class="badge filter badge-primary active" data-color="primary"></span>
              <span class="badge filter badge-info" data-color="blue"></span>
              <span class="badge filter badge-success" data-color="green"></span>
            </div>
            <div class="clearfix"></div>
          </a>
        </li>
        <li class="adjustments-line text-center color-change">
          <span class="color-label">LIGHT MODE</span>
          <span class="badge light-badge mr-2"></span>
          <span class="badge dark-badge ml-2"></span>
          <span class="color-label">DARK MODE</span>
        </li>
              
      </ul>

      <br />
    </div>
  </div>
  

core/templates/includes/footer.html
  <footer class="footer">
    <div class="container-fluid">
      <ul class="nav">
        <li class="nav-item">
          <a target="_blank" 
             href="https://www.creative-tim.com/product/black-dashboard-django" class="nav-link">
             Salhi Fayza 2021
          </a>
        </li>
      </ul>
      <div class="copyright">
        &copy; <a target="_blank" 
                  href="https://www.creative-tim.com/">Creative-Tim</a>
         - coded by <a target="_blank" href="https://appseed.us?ref=ct-demo">AppSeed</a>.
      </div>
    </div>
  </footer>

core/templates/includes/navigation-rtl.html
<!-- Static assets -->
{% load static %}

      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="javascript:void(0)">RTL</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse" id="navigation">
            <ul class="navbar-nav  mr-auto">
              <li class="search-bar input-group">
                <button class="btn btn-link" id="search-button" data-toggle="modal" data-target="#searchModal"><i class="tim-icons icon-zoom-split" ></i>
                  <span class="d-lg-none d-md-block">Search</span>
                </button>
              </li>
              <li class="dropdown nav-item">
                <a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="notification d-none d-lg-block d-xl-block"></div>
                  <i class="tim-icons icon-sound-wave"></i>
                  <p class="d-lg-none">
                    Notifications
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-menu-right dropdown-navbar">
                  <li class="nav-link"><a href="#" class="nav-item dropdown-item">Mike John responded to your email</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">You have 5 more tasks</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Your friend Michael is in town</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another notification</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another one</a></li>
                </ul>
              </li>
              <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="photo">
                    <img src="{% static 'assets/img/fayzza.png' %}" alt="Profile Photo">
                  </div>
                  <b class="caret d-none d-lg-block d-xl-block"></b>
                  <p class="d-lg-none">
                    Log out
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-navbar">
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Profile</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Settings</a></li>
                  <li class="dropdown-divider"></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Log out</a></li>
                </ul>
              </li>
              <li class="separator d-lg-none"></li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <i class="tim-icons icon-simple-remove"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- End Navbar -->

core/templates/includes/scripts-sidebar.html
  <script>
    $(document).ready(function() {
      $().ready(function() {
        $sidebar = $('.sidebar');
        $navbar = $('.navbar');
        $main_panel = $('.main-panel');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');
        sidebar_mini_active = true;
        white_color = false;

        window_width = $(window).width();

        fixed_plugin_open = $('.sidebar .sidebar-wrapper .nav li.active a p').html();



        $('.fixed-plugin a').click(function(event) {
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .background-color span').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data', new_color);
          }

          if ($main_panel.length != 0) {
            $main_panel.attr('data', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data', new_color);
          }
        });

        $('.switch-sidebar-mini input').on("switchChange.bootstrapSwitch", function() {
          var $btn = $(this);

          if (sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            sidebar_mini_active = false;
            blackDashboard.showSidebarMessage('Sidebar mini deactivated...');
          } else {
            $('body').addClass('sidebar-mini');
            sidebar_mini_active = true;
            blackDashboard.showSidebarMessage('Sidebar mini activated...');
          }

          // we simulate the window Resize so the charts will get updated in realtime.
          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          // we stop the simulation of Window Resize after the animations are completed
          setTimeout(function() {
            clearInterval(simulateWindowResize);
          }, 1000);
        });

        $('.switch-change-color input').on("switchChange.bootstrapSwitch", function() {
          var $btn = $(this);

          if (white_color == true) {

            $('body').addClass('change-background');
            setTimeout(function() {
              $('body').removeClass('change-background');
              $('body').removeClass('white-content');
            }, 900);
            white_color = false;
          } else {

            $('body').addClass('change-background');
            setTimeout(function() {
              $('body').removeClass('change-background');
              $('body').addClass('white-content');
            }, 900);

            white_color = true;
          }


        });

        $('.light-badge').click(function() {
          $('body').addClass('white-content');
        });

        $('.dark-badge').click(function() {
          $('body').removeClass('white-content');
        });
      });
    });
  </script>
  

core/templates/index.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="container">
  <center><h1>Live Data from Arduino connected with the sensors</h1></center>
  <hr/>

  <div class="row d-flex justify-content-center">
    <div class="col-md-4"><label>Enter Com Port:</label></div>
        <div class="col-md-4" >
            <input type="text" class="form-control col-md-2" name="com" id="comport">
        </div>
    <div class="col-md-4">
      <input
        value="Live Data from Arduino"
        type="submit"
        name="submit"
        id="btn_show_chart1"
        class="btn btn-primary"
        
      />
    </div>
  </div>

  <br />
  <hr />
  <div class="row">
    <div id="chartContainer1"></div>
  </div>
  <div style="margin-top: 40%" class="row">
    <div id="chartContainer2"></div>
  </div>
  <div style="margin-top: 40%" class="row">
    <div id="chartContainer3"></div>
  </div>
  <div style="margin-top: 40%" class="row">
    <div id="chartContainer4"></div>
  </div>
</div>

  <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

  <script>
    $("#btn_show_chart1").click(function () {
      com=$("#comport").val();
      fill_graph_sensor1(com);
      fill_graph_sensor2(com);
      fill_graph_sensor3(com);
      fill_graph_sensor4(com);
    });
    function fill_graph_sensor1() {
      var dps = []; // dataPoints
      var chart = new CanvasJS.Chart("chartContainer1",{
        animationEnabled: true,
        title: {
          text: "Charts Humidity ",
          fontFamily: "arial black",
		      fontColor: "#FF6384"
        },
        axisX: {
          title: "Time",
        },
        axisY: {
          title: "Humidity",
          suffix: "%",
		      includeZero: true,
          
          maximum : 100,
        },
        data: [
          {
            type: "spline",
            name: "CPU Utilization",
            connectNullData: true,
            color: "#FF6384",
            xValueType: "dateTime",
            xValueFormatString: "DD MMM hh:mm TT",
            yValueFormatString: '#,##0.##"%"',
            dataPoints: dps,
          },
        ],
      });
      var xVal = 0;
      var yVal = 100;
      var updateInterval = 4000; //miliseconds
      var dataLength = 100; // number of dataPoints visible at any point
      var updateChart = function () {
        $.ajax({
          type: "get",
          url: "{% url 'app:fetch_sensor_values_ajax_com' %}",
          data: {
                     'id': com
                   },
          success: function (data) {
            console.log(data.result);
            var str_array = data.result[0].split(",");
            console.log(str_array);
            dps.push({
              x: Date.parse(str_array[1]),
              y: Number(str_array[0]),
            });

            return data;
          },
          error: function () {
            console.log("error he ji");
          },
        });
        if (dps.length > dataLength) {
          dps.shift();
        }
        chart.render();
      };
      updateChart(dataLength);
      setInterval(function () {
        updateChart();
      }, updateInterval);
    }
    function fill_graph_sensor2() {
      var dps = []; // dataPoints
      var chart = new CanvasJS.Chart("chartContainer2", {
        animationEnabled: true,
        title: {
          text: "Charts Temperature ",
          fontFamily: "arial black",
		      fontColor: "#4BC0C0"
        },
        axisX: {
          title: "Time",
        },
        axisY: {
          title: "Temperature",
          suffix: "°C",
          viewportMinimum: -80,
          viewportMaximum: 80
          
        },
        data: [
          {
            type: "spline",
            name: "CPU Utilization",
            connectNullData: true,
            color: "#4BC0C0",
            xValueType: "dateTime",
            xValueFormatString: "DD MMM hh:mm TT",
            yValueFormatString: '#,##0.##"°C"',
            dataPoints: dps,
          },
        ],
      });
      var xVal = 0;
      var yVal = 100;
      var updateInterval = 4000; //miliseconds
      var dataLength = 20; // number of dataPoints visible at any point
      var updateChart = function () {
        $.ajax({
          type: "get",
          url: "{% url 'app:fetch_sensor_values_ajax_com' %}",
          data: {
                     'id': com
                   },
          success: function (data) {
            console.log(data.result);
            var str_array = data.result[1].split(",");
            console.log(str_array);

            dps.push({
              x: Date.parse(str_array[1]),
              y: Number(str_array[0]),
            });

            return data;
          },
          error: function () {
            console.log("error he ji");
          },
        });
        if (dps.length > dataLength) {
          dps.shift();
        }
        chart.render();
      };
      updateChart(dataLength);
      setInterval(function () {
        updateChart();
      }, updateInterval);
    }
    function fill_graph_sensor3() {
      var dps = []; // dataPoints
      var chart = new CanvasJS.Chart("chartContainer3", {
        animationEnabled: true,
       
        
        title: {
          text: "Charts WaterTemp ",
          fontFamily: "arial black",
		      fontColor: "#FFCE56"
        },
        axisX: {
          title: "Time",
        },
        axisY: {
          title: "WaterTemp",
          suffix: "°C",
          viewportMinimum: -170,
          viewportMaximum: 170
        },
        data: [
        {
            type: "spline",
            name: "CPU Utilization",
            connectNullData: true,
            color: "#FFCE56",
            xValueType: "dateTime",
            xValueFormatString: "DD MMM hh:mm TT",
            yValueFormatString: '#,##0.##"°C"',
            dataPoints: dps,
          },
        ],
      });
     
      var xVal = 0;
      var yVal = 100;
      var updateInterval = 4000; //miliseconds
      var dataLength = 20; // number of dataPoints visible at any point
      var updateChart = function () {
        $.ajax({
          type: "get",
          url: "{% url 'app:fetch_sensor_values_ajax_com' %}",
          data: {
                     'id': com
                   },
          success: function (data) {
            console.log(data.result);
            var str_array = data.result[2].split(",");
            console.log(str_array);

            dps.push({
              x: Date.parse(str_array[1]),
              y: Number(str_array[0]),
            });

            return data;
          },
          error: function () {
            console.log("error he ji");
          },
        });
        if (dps.length > dataLength) {
          dps.shift();
        }
        chart.render();
      };
      updateChart(dataLength);
      setInterval(function () {
        updateChart();
      }, updateInterval);
    }
    function fill_graph_sensor4() {
      var dps = []; // dataPoints
      var chart = new CanvasJS.Chart("chartContainer4", {
        animationEnabled: true,
        title: {
          text: "Charts pH ",
          fontFamily: "arial black",
		      fontColor: "#36A2EB"
        },
        axisX: {
          title: "Time",
        },
        axisY: {
          title: "pH",
          suffix: "",
		       includeZero: true,
          maximum : 15,
        },
        data: [
          {
            type: "spline",
            name: "pH",
            connectNullData: true,
            color: "#36A2EB",
            xValueType: "dateTime",
            xValueFormatString: "DD MMM hh:mm TT",
            yValueFormatString: '#,##0.##""',
            dataPoints: dps,
          },
        ],
      });
      var xVal =0;
      var yVal = 100;
      var updateInterval = 4000; //miliseconds
      var dataLength = 20; // number of dataPoints visible at any point
      var updateChart = function () {
        $.ajax({
          type: "get",
          url: "{% url 'app:fetch_sensor_values_ajax_com' %}",
          data: {
                     'id': com
                   },
          success: function (data) {
            console.log(data.result);
            var str_array = data.result[3].split(",");
            console.log(str_array);

            dps.push({
              x: Date.parse(str_array[1]),
              y: Number(str_array[0]),
            });

            return data;
          },
          error: function () {
            console.log("error he ji");
          },
        });
        if (dps.length > dataLength) {
          dps.shift();
        }
        chart.render();
      };
      updateChart(dataLength);
      setInterval(function () {
        updateChart();
      }, updateInterval);
    }
  </script>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      demo.initDashboardPageCharts();

    });
  </script>

{% endblock javascripts %}